const profiles = [{ 
    name : "RAFAEL SUÁREZ",
    bio : 'Dr. Rafael Suárez, Profesor Adjunto del Depto. de Arqueología del Instituto de Ciencias Antropológicas de la Facultad de Humanidades y Ciencias de la Educación. Coordinador y responsable del grupo de investigación: <a href="https://formularios.csic.edu.uy/grupos/formulario/PrincipalAction.action?comando=ficha_completa&id=883045">“Los primeros americanos en Uruguay: arqueología prehistórica durante el final del Pleistoceno”</a> (CSIC 883045) (link del grupo). Investiga desde hace más de 20 años el poblamiento temprano en Uruguay, focalizándose en diferentes temáticas y líneas de investigación: tecnología lítica, movilidad y uso del espacio, innovaciones tecnológicas, cambio cultural, prestigio social/individual entre los grupos tempranos, fuentes de aprovisionamiento de materias primas, entre otros. Entre 2000-2006 fue responsable científico de las excavaciones en el sitio Pay Paso 1. Desde el año 2013 dirige los trabajos y excavaciones arqueológicas en el sitio Tigre (río Uruguay). Comenzó a partir del año 2017 la investigación de sitios en aleros y cuevas en el centro de Uruguay. Viene formando a la nueva generación de arqueólogas/os de Uruguay que se interesan por el tema del poblamiento temprano y tecnología lítica. Ha realizado una extensa serie de publicaciones en revistas internacionales, así como es editor del libro <a href="https://uofupress.lib.utah.edu/people-and-culture-in-ice-age-americas/">“People and Culture in Ice Age Americas: New Dimensions in Paleoamerican Archaeology”</a> editado por Utah University Press',    
    img : "media/rafa.jpeg"
},
{name: "BRUCE BRADLEY",
bio: 'Doctor en Antropología por la University of Cambridge, England. Es un investigador que se ha vuelto una leyenda de la arqueología mundial debido a su profundo y amplio conocimiento en relación a la tecnología lítica. Investiga desde hace más de 50 años el poblamiento de América, tiene un conocimiento profundo de la tecnología lítica, es un maestro de la talla donde ha desarrollado a niveles muy altos la arqueología experimental. Desarrolló un modelo sobre el poblamiento de América en su libro “Across Atlantic Ice”.',
img: "media/rafa.jpeg"},
,
{ 
    name : "FLORENCIA BARCELÓ",
    bio : 'Nació en el seno de una familia de clase media acomodada polaca. Hijo de Lucjan Malinowski, un eslavista especializado en el dialecto polaco de Silesia. Durante su niñez sufrió de los achaques de una salud frágil. En 1897 su madre viajó con él por los países del sur europeo, por cuestiones de salud. En 1903 comienza a estudiar filosofía en la Universidad de Cracovia, doctorándose en 1908, especializándose en física y matemáticas. Se traslada a Leipzig (Alemania) para profundizar sus conocimientos en psicología y economía bajo la dirección de C. G. Seligman. La lectura de The Golden Bough (La rama dorada) de James Frazer volcó su interés hacia la Antropología Social lo que le llevó a Inglaterra para formarse en esta disciplina, obteniendo su grado en la London School of Economics en 1910. Fue profesor en esta Universidad desde 1913, y allí se doctoró en 1916. En 1914 viajó a Papúa (actual Papúa Nueva Guinea), donde llevó adelante un trabajo de campo en Mailu y en las islas Trobriand. Como súbdito del Imperio austrohúngaro en territorio bajo jurisdicción británica, la declaración de la Primera Guerra Mundial lo obligó a aceptar el destierro en las islas Trobriand hasta que acabase la guerra. Aquí es donde realizó su trabajo de campo acerca del kula y comenzó a ',
    img : "media/flor.jpeg"
},
{ 
    name : "RAFAEL SUÁREZ",
    bio : 'Dr. Rafael Suárez, Profesor Adjunto del Depto. de Arqueología del Instituto de Ciencias Antropológicas de la Facultad de Humanidades y Ciencias de la Educación. Coordinador y responsable del grupo de investigación: <a href="https://formularios.csic.edu.uy/grupos/formulario/PrincipalAction.action?comando=ficha_completa&id=883045">“Los primeros americanos en Uruguay: arqueología prehistórica durante el final del Pleistoceno”</a> (CSIC 883045) (link del grupo). Investiga desde hace más de 20 años el poblamiento temprano en Uruguay, focalizándose en diferentes temáticas y líneas de investigación: tecnología lítica, movilidad y uso del espacio, innovaciones tecnológicas, cambio cultural, prestigio social/individual entre los grupos tempranos, fuentes de aprovisionamiento de materias primas, entre otros. Entre 2000-2006 fue responsable científico de las excavaciones en el sitio Pay Paso 1. Desde el año 2013 dirige los trabajos y excavaciones arqueológicas en el sitio Tigre (río Uruguay). Comenzó a partir del año 2017 la investigación de sitios en aleros y cuevas en el centro de Uruguay. Viene formando a la nueva generación de arqueólogas/os de Uruguay que se interesan por el tema del poblamiento temprano y tecnología lítica. Ha realizado una extensa serie de publicaciones ',
    img : "media/2.jpeg"
},
{ 
    name : "TRES PERSONAS",
    bio : 'Nació en el seno de una familia de clase media acomodada polaca. Hijo de Lucjan Malinowski, un eslavista especializado en el dialecto polaco de Silesia. Durante su niñez sufrió de los achaques de una salud frágil. En 1897 su madre viajó con él por los países del sur europeo, por cuestiones de salud. En 1903 comienza a estudiar filosofía en la Universidad de Cracovia, doctorándose en 1908, especializándose en física y matemáticas. Se traslada a Leipzig (Alemania) para profundizar sus conocimientos en psicología y economía bajo la dirección de C. G. Seligman. La lectura de The Golden Bough (La rama dorada) de James Frazer volcó su interés hacia la Antropología Social lo que le llevó a Inglaterra para formarse en esta disciplina, obteniendo su grado en la London School of Economics en 1910. Fue profesor en esta Universidad desde 1913, y allí se doctoró en 1916. En 1914 viajó a Papúa (actual Papúa Nueva Guinea), donde llevó adelante un trabajo de campo en Mailu y en las islas Trobriand. Como súbdito del Imperio austrohúngaro en territorio bajo jurisdicción británica, la declaración de la Primera Guerra Mundial lo obligó a aceptar el destierro en ',
    img : "media/tres.jpeg"
},
{ 
    name : "RAFAEL SUÁREZ",
    bio : 'Dr. Rafael Suárez, Profesor Adjunto del Depto. de Arqueología del Instituto de Ciencias Antropológicas de la Facultad de Humanidades y Ciencias de la Educación. Coordinador y responsable del grupo de investigación: <a href="https://formularios.csic.edu.uy/grupos/formulario/PrincipalAction.action?comando=ficha_completa&id=883045">“Los primeros americanos en Uruguay: arqueología prehistórica durante el final del Pleistoceno”</a> (CSIC 883045) (link del grupo). Investiga desde hace más de 20 años el poblamiento temprano en Uruguay, focalizándose en diferentes temáticas y líneas de investigación: tecnología lítica, movilidad y uso del espacio, innovaciones tecnológicas, cambio cultural, prestigio social/individual entre los grupos tempranos, fuentes de aprovisionamiento de materias primas, entre otros. Entre 2000-2006 fue responsable científico de las excavaciones en el sitio Pay Paso 1. Desde el año 2013 dirige los trabajos y excavaciones arqueológicas en el sitio Tigre (río Uruguay). Comenzó a partir del año 2017 la investigación de sitios en aleros y cuevas en el centro de Uruguay. Viene formando a la nueva generación de arqueólogas/os de Uruguay que ',
    img : "media/2.jpeg"
},
{ 
    name : "MALINOWSKI",
    bio : 'Nació en el seno de una familia de clase media acomodada polaca. Hijo de Lucjan Malinowski, un eslavista especializado en el dialecto polaco de Silesia. Durante su niñez sufrió de los achaques de una salud frágil. En 1897 su madre viajó con él por los países del sur europeo, por cuestiones de salud. En 1903 comienza a estudiar filosofía en la Universidad de Cracovia, doctorándose en 1908, especializándose en física y matemáticas. Se traslada a Leipzig (Alemania) para profundizar sus conocimientos en psicología y economía bajo la dirección de C. G. Seligman. La lectura de The Golden Bough (La rama dorada) de James Frazer volcó su interés hacia la Antropología Social lo que le llevó a Inglaterra para formarse en esta disciplina, obteniendo su grado en la London School of Economics en 1910. Fue profesor en esta Universidad desde 1913, y allí se doctoró en 1916. En 1914 viajó a Papúa (actual Papúa Nueva Guinea), donde llevó adelante un trabajo de campo en Mailu y en las islas Trobriand. Como súbdito del Imperio austrohúngaro en territorio bajo jurisdicción británica, la declaración de la Primera Guerra Mundial lo obligó a aceptar el destierro en ',
    img : "media/2.jpeg"
},
]
export default profiles